version: '2'

services:
  nginx:
    image: nginx:1.21.5-alpine
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/cert/:/etc/nginx/cert/
    ports:
      - 80:80
      - 443:443
  kurento:
    image: kurento/kurento-media-server:7.0.0
    container_name: kurento
    # network_mode: host
    ports:
      - "8888:8888/tcp"
      - "5001-5050:5001-5050/udp"
    volumes:
      - ./storage/kurento:/storage:rw
    environment:
      KMS_UID: 1000
      KMS_MIN_PORT: 5000
      KMS_MAX_PORT: 5050
      G_DEBUG: fatal-warnings
      GST_DEBUG: 4,Kurento*:4,kms*:4,sdp*:4,webrtc*:4,*rtpendpoint:4,rtp*handler:4,rtpsynchronizer:4,agnosticbin:4,KurentoMediaElementImpl:5,agnosticbin*:5,KurentoMediaElementImpl:5,webrtcendpoint:5,kmswebrtcsession:5,kmsiceniceagent:5,KurentoUriEndpointImpl:5,uriendpoint:5,GST_URI:6,KurentoRecorderEndpointImpl:5,recorderendpoint:5,basemediamuxer:5,curl*:6
      #KURENTO_TURN_URL: turn:coturn:5349
      #KURENTO_TURN_USERNAME: fermi
      #KURENTO_TURN_PASSWORD: fermi1004
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/data:/data
    command: redis-server --port 6379 --requirepass "fermi1004@!"
  mariadb:
    image: mariadb:10.5.9
    container_name: mariadb 
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb/data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4' # conf.d 우선
      - '--collation-server=utf8mb4_unicode_ci' # conf.d 우선
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: tjfgus1!
      MYSQL_DATABASE: coview_meta
      MYSQL_USER: pantheon
      MYSQL_PASSWORD: tjfgus1!
  # mariadb
  # redis
