version: "3"
services:
  redis-cluster:
    hostname: redis-cluster
    platform: linux/amd64
    image: redis:7.2.3
    container_name: redis-main-cluster
    ports:
      - "16301:16301"
      - "16401:16401"
      - "6301:6301"
      - "6401:6401"
      - "6371:6379"
  redis-for-cluster-ms-1:
    build:
      dockerfile: ./Dockerfile
      context: ./
    container_name: redis-for-cluster-ms-6301
    image: redis:7.2.3
    user: root
    platform: linux/x86_64
    network_mode: "service:redis-cluster"
    volumes:
#      - ./redis/redis-7.2.3/redis_6301.conf:/redis/redis.conf
#      - ./redis/redis-7.2.3/logs:/redis/logs
#      - ./redis/redis-7.2.3/entrypoint.sh:/data/entrypoint.sh
      - /home/fermi/redis/redis_6301.conf:/redis/redis.conf
      - /home/fermi/redis/logs:/redis/logs
      - /home/fermi/redis/entrypoint.sh:/redis/entrypoint.sh
    working_dir: /data
  redis-for-cluster-ms-2:
    build:
      dockerfile: ./Dockerfile
      context: ./
    container_name: redis-for-cluster-ms-6401
    image: redis:7.2.3
    user: root
    network_mode: "service:redis-cluster"
    volumes:
#      - ./redis/redis-7.2.3/redis_6401.conf:/redis/redis.conf
#      - ./redis/redis-7.2.3/logs:/redis/logs
#      - ./redis/redis-7.2.3/entrypoint.sh:/data/entrypoint.sh
      - /home/fermi/redis/redis_6401.conf:/redis/redis.conf
      - /home/fermi/redis/logs:/redis/logs
      - /home/fermi/redis/entrypoint.sh:/redis/entrypoint.sh
    working_dir: /data