version: '1'
services:
  kurento-container:
    networks:
      kuren:
        ipv4_address: 172.25.0.3
    container_name: kurento-media-server
    build:
      dockerfile:
        ./docker/kurento/Dockerfile
    ports:
      - "8888:8888"
  kurento-server:
    networks:
      kuren:
        ipv4_address: 172.25.0.2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command:
#      - "ssh -L 8888:localhost:8888 fermi@devpt.coview.co.kr -y"
    environment:
      - MYSQL_ROOT_PASSWORD=eddy
    ports:
      - "8090:8090"
    build:
      dockerfile:
        ./docker/Dockerfile
      args:
        env: "development"
    container_name: kurento-recording
    volumes:
      - ./:/kurento
networks:
  kuren:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16