version: '1'
services:
  kurento-server:
    command:
#      - "sudo su"
#      - "sudo source /etc/bash.bashrc"
    environment:
      - MYSQL_ROOT_PASSWORD=eddy
    ports:
      - "8090:8080"
    build:
      dockerfile:
        ./docker/Dockerfile
      args:
        env: "development"
    container_name: kurento-recording
    volumes:
      - ./:/home/