server:
  port: 8899

logging:
  level:
    org.springframework.web: trace



spring:
  reactor:
    debug-agent:
      enabled: true
  data:
    redis:
      port: 6379
  integration:
    management:
      default-logging-enabled: true

